apiVersion: apps/v1
kind: Deployment
metadata:
  name: backoffice-be
spec:
  template:
    spec:
      containers:
        - name: backoffice-be
          env:
            - name: dbDdlAuto
              value: update
            - name: dbSeedData
              value: "true"