apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-gateway
spec:
  template:
    spec:
      containers:
        - name: payment-gateway
          env:
            - name: dbDdlAuto
              value: update