kind: Secret
apiVersion: v1
metadata:
  name: github-creds
  annotations:
    tekton.dev/git-0: "https://github.com"
stringData:
  username: andrianrf
  password: changeme
type: kubernetes.io/basic-auth