kind: Secret
apiVersion: v1
metadata:
  name: docker-creds
  annotations:
    tekton.dev/docker-0: "https://docker.io"
stringData:
  username: andrianrf
  password: changeme
type: kubernetes.io/basic-auth